FROM node:18-alpine

WORKDIR '/app'

COPY  ./package.json .


#Add `/app/node_modules/.bin` to $PATH
#PATH /app/node_modules/.bin:$PATH

RUN npm install 

COPY  . .
#COPY . . 

CMD ["npm" , "run"  , "start"]
# Deploy app for local development
#CMD npm start --host 0.0.0.0 --port 3000 --disableHostCheck true


